# Generated by Django 4.2.7 on 2023-11-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0002_image_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
