# Generated by Django 4.2.7 on 2023-11-27 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0003_image_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
